{
 "title": "LODA Rust",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Iterations per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(lodarust_mine_iterations_total{}[$__interval])",
     "legendFormat": "1s average"
    },
    {
     "expr": "irate(lodarust_mine_iterations_total{}[$__interval])",
     "legendFormat": "10s average"
    }
   ]
  },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodarust_mine_iterations_now" }
   ]
  },
  {
   "title": "Candidate programs found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodarust_mine_candiate_programs"
    }
   ]
  },
  {
   "title": "Cache hit/miss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lodarust_mine_cache_miss_program_oeis_total[2s])",
     "legendFormat": "Miss OEIS program"
    },
    {
     "expr": "rate(lodarust_mine_cache_miss_program_without_id_total[2s])",
     "legendFormat": "Miss program without id"
    },
    {
     "expr": "rate(lodarust_mine_cache_hit_total[2s])",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Number of workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodarust_mine_workers" }
   ]
  },
  {
   "title": "Funnel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodarust_mine_funnel_10terms_total[2s])",
     "legendFormat": "10 Terms"
    },
    {
     "expr": "rate(lodarust_mine_funnel_20terms_total[2s])",
     "legendFormat": "20 Terms"
    },
    {
     "expr": "rate(lodarust_mine_funnel_30terms_total[2s])",
     "legendFormat": "30 Terms"
    },
    {
     "expr": "rate(lodarust_mine_funnel_40terms_total[2s])",
     "legendFormat": "40 Terms"
    },
    {
     "expr": "sum(rate(lodarust_mine_funnel_false_positive_total[$__rate_interval]))",
     "legendFormat": "False positives"
    }
   ]
  },
  {
   "title": "Mining stats",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodarust_mine_reject_cannot_be_parsed_total[2s])",
     "legendFormat": "Cannot be parsed"
    },
    {
     "expr": "rate(lodarust_mine_reject_no_output_register_total[2s])",
     "legendFormat": "No output register"
    },
    {
     "expr": "rate(lodarust_mine_reject_compute_error_total[2s])",
     "legendFormat": "Compute error"
    },
    {
     "expr": "rate(lodarust_mine_error_genome_load_total[2s])",
     "legendFormat": "Genome load"
    },
    {
     "expr": "rate(lodarust_mine_reject_too_short_total[2s])",
     "legendFormat": "Too short"
    },
    {
     "expr": "rate(lodarust_mine_rejected_preventing_flooding_total[2s])",
     "legendFormat": "Prevented flooding"
    },
    {
     "expr": "rate(lodarust_mine_reject_self_dependency_total[2s])",
     "legendFormat": "Self dependency"
    }
   ]
  },
  {
   "title": "Mutation efficiency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(lodarust_mine_reject_mutate_without_impact_total[$__rate_interval]))",
     "legendFormat": "Mutate without effect"
    }
   ]
  }
 ]
}