//! ARC challenge experiments
mod arc_json_model;
mod arc_puzzles;
mod bitmap;
mod bitmap_to_number;
mod bitmap_try_create;
mod convolution2x2;
mod convolution3x3;
mod convolution_with_program;
mod find;
mod histogram;
mod index_for_pixel;
mod padding;
mod number_to_bitmap;
mod read_testdata;
mod resize;
mod remove_duplicates;
mod replace_color;
mod rotate;
mod symmetry;
mod test_convert;
mod trim;

pub use arc_json_model::{Grid, GridToBitmap, Model, TaskPair};
pub use bitmap::Bitmap;
pub use bitmap_to_number::BitmapToNumber;
pub use bitmap_try_create::BitmapTryCreate;
pub use convolution2x2::convolution2x2;
pub use convolution3x3::convolution3x3;
pub use find::BitmapFind;
pub use histogram::BitmapHistogram;
pub use number_to_bitmap::NumberToBitmap;
pub use padding::Padding;
pub use read_testdata::read_testdata;
pub use replace_color::BitmapReplaceColor;
pub use resize::BitmapResize;
pub use remove_duplicates::BitmapRemoveDuplicates;
pub use rotate::BitmapRotate;
pub use symmetry::BitmapSymmetry;
pub use trim::BitmapTrim;
